# Generated by Django 5.0.1 on 2024-01-16 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signupapis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersignupdatamodal',
            name='user_created_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
