# Generated by Django 5.0.1 on 2024-01-25 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0002_alter_usersignupdatamodal_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersignupdatamodal',
            name='user_email',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
